-- One-time data migration from the local NexaFi SQLite database.
-- Generated by scripts/migrate-nexafi-sqlite.py. Run AFTER finance_setup.sql.
--
-- Safe to re-run only against an empty finance database: it inserts rows with
-- explicit ids and will collide with anything already imported.

do $$
declare
  owner_id uuid;
begin
  select id into owner_id from auth.users where email = 'nhambleton03@gmail.com';
  if owner_id is null then
    raise exception 'No Supabase auth user with email nhambleton03@gmail.com. Create the account first, then re-run.';
  end if;

  -- accounts -> fin_accounts (7 rows)
  insert into public.fin_accounts (owner, "id", "name", "account_type", "institution", "is_liability", "include_in_net_worth", "is_active", "cashback_rate", "statement_balance", "statement_closing_day", "payment_due_day", "created_at", "updated_at") values
    (owner_id, 1, 'Everyday Checking', 'checking', null, false, true, true, 0, 0, null, null, '2026-08-23 20:52:57.469855', '2026-08-23 20:52:57.469859'),
    (owner_id, 2, 'Primary Savings', 'savings', null, false, true, true, 0, 0, null, null, '2026-08-23 20:52:57.469861', '2026-08-23 20:52:57.469862'),
    (owner_id, 3, 'Primary 2% Card', 'credit_card', null, true, true, true, 2, 842.17, 27, 22, '2026-08-23 20:52:57.470208', '2026-08-23 20:52:57.470210'),
    (owner_id, 4, 'Subscription Card', 'credit_card', null, true, true, true, 1, 40, 2, 27, '2026-08-23 20:52:57.470212', '2026-08-23 20:52:57.470213'),
    (owner_id, 5, 'Roth 401(k)', 'retirement', null, false, true, true, 0, 0, null, null, '2026-08-23 20:52:57.470324', '2026-08-23 20:52:57.470326'),
    (owner_id, 6, 'Roth IRA', 'retirement', null, false, true, true, 0, 0, null, null, '2026-08-23 20:52:57.470327', '2026-08-23 20:52:57.470329'),
    (owner_id, 7, 'Taxable Brokerage', 'brokerage', null, false, true, true, 0, 0, null, null, '2026-08-23 20:52:57.470330', '2026-08-23 20:52:57.470333');

  -- transaction_categories -> fin_transaction_categories (22 rows)
  insert into public.fin_transaction_categories (owner, "id", "name", "parent_id", "is_active") values
    (owner_id, 1, 'Housing & Bills', null, true),
    (owner_id, 2, 'Rent', 1, true),
    (owner_id, 3, 'Utilities', 1, true),
    (owner_id, 4, 'Internet', 1, true),
    (owner_id, 5, 'Subscriptions', 1, true),
    (owner_id, 6, 'Food & Dining', null, true),
    (owner_id, 7, 'Groceries', 6, true),
    (owner_id, 8, 'Dining', 6, true),
    (owner_id, 9, 'Coffee', 6, true),
    (owner_id, 10, 'Transportation', null, true),
    (owner_id, 11, 'Gas', 10, true),
    (owner_id, 12, 'Maintenance', 10, true),
    (owner_id, 13, 'Transit', 10, true),
    (owner_id, 14, 'Shopping & Personal', null, true),
    (owner_id, 15, 'Clothing', 14, true),
    (owner_id, 16, 'Household', 14, true),
    (owner_id, 17, 'Personal Care', 14, true),
    (owner_id, 18, 'Travel & Other', null, true),
    (owner_id, 19, 'Travel', 18, true),
    (owner_id, 20, 'Entertainment', 18, true),
    (owner_id, 21, 'Gifts', 18, true),
    (owner_id, 22, 'Other', 18, true);

  -- account_balances -> fin_account_balances (7 rows)
  insert into public.fin_account_balances (owner, "id", "account_id", "balance_date", "balance", "source", "created_at", "updated_at") values
    (owner_id, 1, 1, '2026-08-23', 4380.4, 'demo', '2026-08-23 20:52:57.472038', '2026-08-23 20:52:57.472040'),
    (owner_id, 2, 2, '2026-08-23', 14000, 'demo', '2026-08-23 20:52:57.472041', '2026-08-23 20:52:57.472042'),
    (owner_id, 3, 3, '2026-08-23', 1092.17, 'demo', '2026-08-23 20:52:57.472043', '2026-08-23 20:52:57.472044'),
    (owner_id, 4, 4, '2026-08-23', 40, 'demo', '2026-08-23 20:52:57.472045', '2026-08-23 20:52:57.472046'),
    (owner_id, 5, 5, '2026-08-23', 18420.55, 'demo', '2026-08-23 20:52:57.472047', '2026-08-23 20:52:57.472048'),
    (owner_id, 6, 6, '2026-08-23', 6240.1, 'demo', '2026-08-23 20:52:57.472051', '2026-08-23 20:52:57.472052'),
    (owner_id, 7, 7, '2026-08-23', 3860.8, 'demo', '2026-08-23 20:52:57.472053', '2026-08-23 20:52:57.472054');

  -- transactions -> fin_transactions (9 rows)
  insert into public.fin_transactions (owner, "id", "transaction_date", "account_id", "description", "amount", "transaction_type", "category_id", "subcategory_id", "notes", "is_transfer", "is_recurring", "source", "fingerprint", "created_at", "updated_at", "posting_date", "merchant", "raw_description", "source_transaction_id", "confidence", "review_required", "ai_import_id") values
    (owner_id, 1, '2026-08-03', 1, 'Monthly salary', 4200, 'income', null, null, null, false, false, 'demo', '7e679de25a59c66f670a3f0a140398db9484ad93760af258826434189e412927', '2026-08-23 20:52:57.474340', '2026-08-23 20:52:57.474341', null, null, null, null, null, false, null),
    (owner_id, 2, '2026-08-04', 1, 'Rent', 1755, 'expense', 1, 2, null, false, true, 'demo', 'c68f1fe2b3f698d1a1678c4599a30c3cc3bfa686170288936d41a6de2097bab3', '2026-08-23 20:52:57.474343', '2026-08-23 20:52:57.474345', null, null, null, null, null, false, null),
    (owner_id, 3, '2026-08-06', 3, 'Harris Teeter', 126.43, 'expense', 6, 7, null, false, false, 'demo', '13944f408b68cbc93d93917587bfbe2f29f04ee149e126b1d465c822b094b475', '2026-08-23 20:52:57.474348', '2026-08-23 20:52:57.474349', null, null, null, null, null, false, null),
    (owner_id, 4, '2026-08-08', 3, 'City Bistro', 64.2, 'expense', 6, 8, null, false, false, 'demo', '2732f222429baf1e7455e4e0098b9b4c7f55365e58b46c37a0e1b1efd52970ac', '2026-08-23 20:52:57.474351', '2026-08-23 20:52:57.474352', null, null, null, null, null, false, null),
    (owner_id, 5, '2026-08-11', 3, 'Shell', 52.1, 'expense', 10, 11, null, false, false, 'demo', 'f3919298fb5b5631762a4a174cd010da621377ec054b51129249c37d4bc0df7a', '2026-08-23 20:52:57.474354', '2026-08-23 20:52:57.474355', null, null, null, null, null, false, null),
    (owner_id, 6, '2026-08-14', 1, 'Home internet', 35, 'expense', 1, 4, null, false, true, 'demo', 'cfcd6c04c418959a05b86275e747b2b194358838d21f096593e1bd19f2a35ba3', '2026-08-23 20:52:57.474360', '2026-08-23 20:52:57.474362', null, null, null, null, null, false, null),
    (owner_id, 7, '2026-08-16', 3, 'Everyday goods', 88.49, 'expense', 14, 16, null, false, false, 'demo', '31f4f36fb3bb876b00fe552601615b29d05a03a644dbd6ebb8dc9a34a159d0ee', '2026-08-23 20:52:57.474363', '2026-08-23 20:52:57.474364', null, null, null, null, null, false, null),
    (owner_id, 8, '2026-08-18', 3, 'Weekend tickets', 72, 'expense', 18, 20, null, false, false, 'demo', 'f761c66ed8d538b28f670448485aae58f6c377a057ba215c8c0a1d7004752288', '2026-08-23 20:52:57.474365', '2026-08-23 20:52:57.474366', null, null, null, null, null, false, null),
    (owner_id, 9, '2026-08-20', 1, 'Card payment', 780, 'card_payment', null, null, null, true, false, 'demo', '8702eb1370f35fbbbadcb4e5b75be1849726a652ba991553f2735ec65d3cf465', '2026-08-23 20:52:57.474367', '2026-08-23 20:52:57.474369', null, null, null, null, null, false, null);

  -- recurring_expenses -> fin_recurring_expenses (7 rows)
  insert into public.fin_recurring_expenses (owner, "id", "name", "amount", "frequency", "due_day", "is_variable", "category_id", "account_id", "is_active", "created_at", "updated_at") values
    (owner_id, 1, 'Rent', 1755, 'monthly', 1, false, 2, 1, true, '2026-08-23 20:52:57.473307', '2026-08-23 20:52:57.473308'),
    (owner_id, 2, 'Electricity', 90, 'monthly', 15, true, 3, 1, true, '2026-08-23 20:52:57.473310', '2026-08-23 20:52:57.473311'),
    (owner_id, 3, 'Home internet', 35, 'monthly', 18, false, 4, 1, true, '2026-08-23 20:52:57.473312', '2026-08-23 20:52:57.473313'),
    (owner_id, 4, 'ChatGPT', 20, 'monthly', 8, false, 5, 1, true, '2026-08-23 20:52:57.473315', '2026-08-23 20:52:57.473316'),
    (owner_id, 5, 'Spotify', 14, 'monthly', 12, false, 5, 1, true, '2026-08-23 20:52:57.473318', '2026-08-23 20:52:57.473319'),
    (owner_id, 6, 'iCloud', 3, 'monthly', 20, false, 5, 1, true, '2026-08-23 20:52:57.473321', '2026-08-23 20:52:57.473322'),
    (owner_id, 7, 'Streaming', 3, 'monthly', 25, false, 5, 1, true, '2026-08-23 20:52:57.473324', '2026-08-23 20:52:57.473325');

  -- sinking_funds -> fin_sinking_funds (1 rows)
  insert into public.fin_sinking_funds (owner, "id", "name", "target_amount", "current_amount", "due_date", "linked_account_id", "is_active", "created_at", "updated_at") values
    (owner_id, 1, 'Car Tax + Inspection', 250, 250, '2026-10-01', 2, true, '2026-08-23 20:52:57.473924', '2026-08-23 20:52:57.473926');

  -- financial_goals -> fin_financial_goals (5 rows)
  insert into public.fin_financial_goals (owner, "id", "name", "goal_type", "target_amount", "current_amount", "recommended_monthly", "user_monthly_target", "target_date", "linked_account_id", "is_active", "created_at", "updated_at") values
    (owner_id, 1, 'Emergency Fund', 'emergency', 10000, 10000, 0, 0, null, 2, true, '2026-08-23 20:52:57.472500', '2026-08-23 20:52:57.472501'),
    (owner_id, 2, 'Travel', 'travel', 3000, 1500, 250, 250, null, 2, true, '2026-08-23 20:52:57.472503', '2026-08-23 20:52:57.472504'),
    (owner_id, 3, 'Future House / Down Payment', 'house', 80000, 2250, 200, 200, null, 2, true, '2026-08-23 20:52:57.472505', '2026-08-23 21:19:16.887636'),
    (owner_id, 4, 'Roth IRA Annual Target', 'retirement', 3600, 0, 300, 300, null, 6, true, '2026-08-23 21:11:30.610648', '2026-08-23 21:11:30.610650'),
    (owner_id, 5, 'Taxable Investing Annual Target', 'taxable', 3600, 0, 300, 300, null, 7, true, '2026-08-23 21:11:30.610650', '2026-08-23 21:11:30.610651');

  -- retirement_contributions -> fin_retirement_contributions (1 rows)
  insert into public.fin_retirement_contributions (owner, "id", "contribution_date", "account_id", "employee_amount", "employer_match", "contribution_type", "created_at", "updated_at") values
    (owner_id, 1, '2026-08-03', 5, 525, 175, 'roth', '2026-08-23 20:52:57.473668', '2026-08-23 20:52:57.473670');

  -- monthly_snapshots -> fin_monthly_snapshots (6 rows)
  insert into public.fin_monthly_snapshots (owner, "id", "snapshot_month", "net_worth", "liquid_cash", "income", "spending", "created_at", "updated_at") values
    (owner_id, 1, '2026-03-01', 42300, 15500, 4200, 2900, '2026-08-23 20:52:57.472870', '2026-08-23 20:52:57.472871'),
    (owner_id, 2, '2026-04-01', 43940, 16076, 4200, 2845, '2026-08-23 20:52:57.472872', '2026-08-23 20:52:57.472874'),
    (owner_id, 3, '2026-05-01', 45580, 16652, 4200, 2790, '2026-08-23 20:52:57.472875', '2026-08-23 20:52:57.472876'),
    (owner_id, 4, '2026-06-01', 47220, 17228, 4200, 2735, '2026-08-23 20:52:57.472879', '2026-08-23 20:52:57.472880'),
    (owner_id, 5, '2026-07-01', 48860, 17804, 4200, 2680, '2026-08-23 20:52:57.472881', '2026-08-23 20:52:57.472882'),
    (owner_id, 6, '2026-08-01', 50500, 18380, 4200, 2625, '2026-08-23 20:52:57.472883', '2026-08-23 20:52:57.472884');

  -- settings -> fin_settings (33 rows)
  insert into public.fin_settings (owner, "id", "key", "value", "value_type", "label", "description", "category", "created_at", "updated_at") values
    (owner_id, 1, 'savings_apy', '2.8', 'decimal', 'Savings APY', 'Annual percentage yield', 'cash', '2026-08-23 20:52:57.470685', '2026-08-23 20:52:57.470687'),
    (owner_id, 2, 'emergency_recommended_target', '10000', 'money', 'Emergency fund recommendation', 'NexaFi baseline recommendation', 'targets', '2026-08-23 20:52:57.470688', '2026-08-23 20:52:57.470689'),
    (owner_id, 3, 'travel_recommended_monthly', '250', 'money', 'Travel monthly recommendation', '$3,000 annual baseline', 'targets', '2026-08-23 20:52:57.470690', '2026-08-23 20:52:57.470691'),
    (owner_id, 4, 'primary_card_payment_day', '22', 'integer', 'Primary card payment day', 'Used for cash-flow timing', 'cash', '2026-08-23 20:52:57.470693', '2026-08-23 20:52:57.470694'),
    (owner_id, 5, 'ira_user_monthly_target', '0', 'money', 'Roth IRA user target', 'Tracking begins in a later phase', 'targets', '2026-08-23 20:52:57.470695', '2026-08-23 20:52:57.470696'),
    (owner_id, 6, 'brokerage_user_monthly_target', '0', 'money', 'Brokerage user target', 'Tracking begins in a later phase', 'targets', '2026-08-23 20:52:57.470697', '2026-08-23 20:52:57.470698'),
    (owner_id, 7, 'house_user_monthly_target', '200', 'money', 'House-fund target', 'Medium/long-term down-payment contribution', 'targets', '2026-08-23 21:11:30.608498', '2026-08-23 21:11:30.608501'),
    (owner_id, 8, 'tax_year', '2026', 'integer', 'Tax year', 'Selects a versioned tax-rule table', 'tax', '2026-08-23 21:11:30.608502', '2026-08-23 21:11:30.608503'),
    (owner_id, 9, 'filing_status', 'single', 'string', 'Filing status', 'Configured rules currently support single filing', 'tax', '2026-08-23 21:11:30.608503', '2026-08-23 21:11:30.608504'),
    (owner_id, 10, 'prior_income', '0', 'money', 'Other-employer income', 'Current-year W-2 income not represented by paychecks', 'tax', '2026-08-23 21:11:30.608504', '2026-08-23 21:11:30.608504'),
    (owner_id, 11, 'prior_federal_withholding', '0', 'money', 'Other federal withholding', 'Current-year federal withholding from other employment', 'tax', '2026-08-23 21:11:30.608505', '2026-08-23 21:11:30.608505'),
    (owner_id, 12, 'prior_virginia_withholding', '0', 'money', 'Other Virginia withholding', 'Current-year Virginia withholding from other employment', 'tax', '2026-08-23 21:11:30.608505', '2026-08-23 21:11:30.608506'),
    (owner_id, 13, 'prior_social_security_wages', '0', 'money', 'Prior Social Security wages', 'Used to apply the annual wage base', 'tax', '2026-08-23 21:11:30.608506', '2026-08-23 21:11:30.608506'),
    (owner_id, 14, 'withholding_tolerance', '25', 'money', 'Withholding audit tolerance', 'Difference per paycheck treated as on track', 'tax', '2026-08-23 21:11:30.608506', '2026-08-23 21:11:30.608507'),
    (owner_id, 15, 'employer_name', 'Newport News Shipbuilding / Huntington Ingalls Industries', 'string', 'Employer', 'Paycheck entry default', 'employment', '2026-08-23 21:11:30.608507', '2026-08-23 21:11:30.608507'),
    (owner_id, 16, 'annual_salary', '84927.44', 'money', 'Annual salary', 'Biweekly gross multiplied by 26', 'employment', '2026-08-23 21:11:30.608508', '2026-08-23 21:11:30.608508'),
    (owner_id, 17, 'pay_periods_per_year', '26', 'integer', 'Pay periods per year', 'Biweekly payroll assumption', 'employment', '2026-08-23 21:11:30.608508', '2026-08-23 21:11:30.608508'),
    (owner_id, 18, 'regular_hours_per_period', '80', 'decimal', 'Regular hours', 'Hours in one pay period', 'employment', '2026-08-23 21:11:30.608509', '2026-08-23 21:11:30.608509'),
    (owner_id, 19, 'annual_pto_hours', '112', 'decimal', 'Annual PTO', 'Annual earned paid time off', 'employment', '2026-08-23 21:11:30.608509', '2026-08-23 21:11:30.608509'),
    (owner_id, 20, 'pto_beginning_balance', '0', 'decimal', 'Beginning PTO balance', 'Balance before recorded paychecks', 'employment', '2026-08-23 21:11:30.608510', '2026-08-23 21:11:30.608510'),
    (owner_id, 21, 'roth_401k_percent', '8', 'decimal', 'Roth 401(k) contribution', 'Post-tax employee contribution percentage', 'retirement', '2026-08-23 21:11:30.608510', '2026-08-23 21:11:30.608511'),
    (owner_id, 22, 'employer_match_percent', '8', 'decimal', 'Employer match', 'Maximum matched percentage of gross pay', 'retirement', '2026-08-23 21:11:30.608511', '2026-08-23 21:11:30.608511'),
    (owner_id, 23, 'current_age', '30', 'integer', 'Current age', 'Editable retirement projection assumption', 'retirement', '2026-08-23 21:11:30.608511', '2026-08-23 21:11:30.608512'),
    (owner_id, 24, 'retirement_age', '65', 'integer', 'Retirement age', 'Projection end age', 'retirement', '2026-08-23 21:11:30.608512', '2026-08-23 21:11:30.608512'),
    (owner_id, 25, 'salary_growth_percent', '3', 'decimal', 'Annual salary growth', 'Projection assumption, not a promise', 'retirement', '2026-08-23 21:11:30.608512', '2026-08-23 21:11:30.608513'),
    (owner_id, 26, 'expected_return_percent', '7', 'decimal', 'Expected return', 'Baseline projection assumption, not a promise', 'retirement', '2026-08-23 21:11:30.608513', '2026-08-23 21:11:30.608513'),
    (owner_id, 27, 'ira_contribution_limit_2026', '7500', 'money', '2026 IRA contribution limit', 'Editable, versioned annual limit', 'retirement', '2026-08-23 21:11:30.608513', '2026-08-23 21:11:30.608514'),
    (owner_id, 28, 'house_horizon_years', '7', 'integer', 'House horizon', 'Editable target horizon in years', 'targets', '2026-08-23 21:11:30.608514', '2026-08-23 21:11:30.608514'),
    (owner_id, 29, 'house_equity_percent', '40', 'decimal', 'House-fund equity allocation', 'Risk assumption; not a recommendation to hold 100% equities', 'targets', '2026-08-23 21:11:30.608514', '2026-08-23 21:11:30.608515'),
    (owner_id, 30, 'house_derisk_years', '3', 'integer', 'House de-risk window', 'Years before target to begin reducing risk', 'targets', '2026-08-23 21:11:30.608515', '2026-08-23 21:11:30.608515'),
    (owner_id, 31, 'retirement_savings_rate_target', '15', 'decimal', 'Retirement savings benchmark', 'Editable comparison target, not a requirement', 'health', '2026-08-23 21:11:30.608516', '2026-08-23 21:11:30.608516'),
    (owner_id, 32, 'total_savings_rate_target', '20', 'decimal', 'Total savings benchmark', 'Editable comparison target, not a requirement', 'health', '2026-08-23 21:11:30.608516', '2026-08-23 21:11:30.608516'),
    (owner_id, 33, 'housing_cost_rate_target', '30', 'decimal', 'Housing-cost benchmark', 'Editable share of gross income, not a requirement', 'health', '2026-08-23 21:11:30.608517', '2026-08-23 21:11:30.608517');

  -- setup_progress absent in the source database
  -- (predates that table); recorded as complete because accounts exist.
  insert into public.fin_setup_progress (owner, current_step, completed, history_option, setup_date, completed_at) values (owner_id, 8, true, 'start_today', current_date, now());

end $$;

-- Move every identity sequence past the highest imported id, so the next
-- row created in the app does not collide with a migrated one.
select public.fin_resync_sequences();
