-- =============================================================================
-- NexaFi / Finance — Supabase setup
-- Run once in the Supabase SQL editor (Dashboard → SQL Editor → New query).
--
-- SECURITY NOTE — this is deliberately different from the other tables in this
-- project. travel_*, drunk_*, etc. allow anonymous read/write because they are
-- low-stakes. This is real financial data, so every table here is:
--   * owner-scoped: an `owner` column pinned to auth.uid()
--   * readable/writable ONLY by an authenticated session whose uid matches
--   * closed to the `anon` role entirely
-- The password box on /finance is a Supabase Auth sign-in, not a cosmetic gate.
-- The anon key being public does NOT expose any row below.
--
-- Tables are prefixed `fin_` because this database is shared with the other
-- sub-apps and names like "accounts"/"settings"/"transactions" would collide.
-- =============================================================================

-- Identity columns are `by default` rather than `always` on purpose: the JSON
-- restore and the one-time migration from the old SQLite database both insert
-- explicit ids, because the foreign keys between these tables only stay intact
-- if the original ids are preserved. Sequences are resynced after such a load
-- with public.fin_resync_sequences().

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

create or replace function public.fin_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Core: accounts, balances, categories, transactions, transfers
-- ---------------------------------------------------------------------------

create table if not exists public.fin_accounts (
  id                    bigint generated by default as identity primary key,
  owner                 uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name                  text not null,
  account_type          text not null,
  institution           text,
  last_four             text,
  is_liability          boolean not null default false,
  include_in_net_worth  boolean not null default true,
  is_active             boolean not null default true,
  cashback_rate         numeric(8,4) not null default 0,
  statement_balance     numeric(14,2) not null default 0,
  statement_closing_day int,
  payment_due_day       int,
  apy                   numeric(8,4) not null default 0,
  autopay_enabled       boolean not null default false,
  payment_account_id    bigint references public.fin_accounts(id) on delete set null,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

create table if not exists public.fin_account_balances (
  id           bigint generated by default as identity primary key,
  owner        uuid not null default auth.uid() references auth.users(id) on delete cascade,
  account_id   bigint not null references public.fin_accounts(id) on delete cascade,
  balance_date date not null,
  balance      numeric(14,2) not null,
  source       text not null default 'manual',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (account_id, balance_date)
);

create table if not exists public.fin_transaction_categories (
  id        bigint generated by default as identity primary key,
  owner     uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name      text not null,
  parent_id bigint references public.fin_transaction_categories(id) on delete cascade,
  is_active boolean not null default true,
  unique (owner, name, parent_id)
);

create table if not exists public.fin_ai_imports (
  id                bigint generated by default as identity primary key,
  owner             uuid not null default auth.uid() references auth.users(id) on delete cascade,
  source_name       text not null,
  status            text not null default 'pending',
  content_hash      text not null,
  source_type       text not null default 'json',
  document_type     text,
  schema_version    text,
  account_id        bigint references public.fin_accounts(id) on delete set null,
  raw_payload       text,
  error_message     text,
  transaction_count int not null default 0,
  duplicate_count   int not null default 0,
  review_count      int not null default 0,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (owner, content_hash)
);

create table if not exists public.fin_transactions (
  id                   bigint generated by default as identity primary key,
  owner                uuid not null default auth.uid() references auth.users(id) on delete cascade,
  transaction_date     date not null,
  posting_date         date,
  account_id           bigint not null references public.fin_accounts(id),
  description          text not null,
  merchant             text,
  raw_description      text,
  source_transaction_id text,
  amount               numeric(14,2) not null,
  transaction_type     text not null,
  category_id          bigint references public.fin_transaction_categories(id) on delete set null,
  subcategory_id       bigint references public.fin_transaction_categories(id) on delete set null,
  notes                text,
  is_transfer          boolean not null default false,
  is_recurring         boolean not null default false,
  source               text not null default 'manual',
  confidence           numeric(5,4),
  review_required      boolean not null default false,
  ai_import_id         bigint references public.fin_ai_imports(id) on delete set null,
  fingerprint          text not null,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  unique (owner, fingerprint)
);

create index if not exists fin_transactions_date_idx     on public.fin_transactions(owner, transaction_date);
create index if not exists fin_transactions_posting_idx  on public.fin_transactions(owner, posting_date);
create index if not exists fin_transactions_merchant_idx on public.fin_transactions(owner, merchant);
create index if not exists fin_transactions_type_idx     on public.fin_transactions(owner, transaction_type);
create index if not exists fin_transactions_transfer_idx on public.fin_transactions(owner, is_transfer);
create index if not exists fin_transactions_import_idx   on public.fin_transactions(ai_import_id);

create table if not exists public.fin_transfers (
  id                        bigint generated by default as identity primary key,
  owner                     uuid not null default auth.uid() references auth.users(id) on delete cascade,
  transfer_date             date not null,
  source_account_id         bigint not null references public.fin_accounts(id),
  destination_account_id    bigint not null references public.fin_accounts(id),
  amount                    numeric(14,2) not null,
  source_transaction_id     bigint not null unique references public.fin_transactions(id) on delete cascade,
  destination_transaction_id bigint not null unique references public.fin_transactions(id) on delete cascade,
  transfer_kind             text not null default 'account_transfer',
  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Income: paychecks + deductions
-- ---------------------------------------------------------------------------

create table if not exists public.fin_paychecks (
  id                     bigint generated by default as identity primary key,
  owner                  uuid not null default auth.uid() references auth.users(id) on delete cascade,
  pay_date               date not null,
  pay_period_start       date,
  pay_period_end         date,
  employer               text not null,
  regular_hours          numeric(8,2) not null default 80,
  gross_amount           numeric(14,2) not null,
  net_amount             numeric(14,2) not null,
  federal_withholding    numeric(14,2) not null default 0,
  virginia_withholding   numeric(14,2) not null default 0,
  social_security        numeric(14,2) not null default 0,
  medicare               numeric(14,2) not null default 0,
  roth_401k              numeric(14,2) not null default 0,
  employer_401k_match    numeric(14,2) not null default 0,
  other_deductions       numeric(14,2) not null default 0,
  pto_earned             numeric(10,4) not null default 0,
  pto_used               numeric(10,4) not null default 0,
  destination_account_id bigint references public.fin_accounts(id) on delete set null,
  notes                  text,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);

create table if not exists public.fin_paycheck_deductions (
  id             bigint generated by default as identity primary key,
  owner          uuid not null default auth.uid() references auth.users(id) on delete cascade,
  paycheck_id    bigint not null references public.fin_paychecks(id) on delete cascade,
  name           text not null,
  deduction_type text not null,
  amount         numeric(14,2) not null,
  is_pre_tax     boolean not null default false
);

-- A logged or planned stretch of time off. Kept separate from fin_paychecks'
-- pto_earned/pto_used (the payroll ledger) because this is a plan, not a pay
-- stub: it exists before payroll ever sees it, and holidays/weekends inside
-- the range don't consume PTO the way they would if this just mirrored a
-- paycheck deduction.
create table if not exists public.fin_pto_entries (
  id             bigint generated by default as identity primary key,
  owner          uuid not null default auth.uid() references auth.users(id) on delete cascade,
  start_date     date not null,
  end_date       date not null,
  hours_per_day  numeric(6,2) not null default 8,
  leave_type     text not null default 'vacation',
  notes          text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  check (end_date >= start_date)
);

create index if not exists fin_pto_entries_dates_idx on public.fin_pto_entries(owner, start_date);

-- ---------------------------------------------------------------------------
-- Recurring money: subscriptions, expenses, sinking funds, goals, retirement
-- ---------------------------------------------------------------------------

create table if not exists public.fin_subscriptions (
  id                bigint generated by default as identity primary key,
  owner             uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name              text not null,
  amount            numeric(14,2) not null,
  billing_frequency text not null default 'monthly',
  next_due_date     date,
  account_id        bigint references public.fin_accounts(id) on delete set null,
  category_id       bigint references public.fin_transaction_categories(id) on delete set null,
  is_active         boolean not null default true,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (owner, name)
);

create table if not exists public.fin_recurring_expenses (
  id          bigint generated by default as identity primary key,
  owner       uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name        text not null,
  amount      numeric(14,2) not null,
  frequency   text not null default 'monthly',
  due_day     int,
  is_variable boolean not null default false,
  category_id bigint references public.fin_transaction_categories(id) on delete set null,
  account_id  bigint references public.fin_accounts(id) on delete set null,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (owner, name)
);

create table if not exists public.fin_sinking_funds (
  id                bigint generated by default as identity primary key,
  owner             uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name              text not null,
  target_amount     numeric(14,2) not null,
  current_amount    numeric(14,2) not null default 0,
  due_date          date,
  linked_account_id bigint references public.fin_accounts(id) on delete set null,
  is_active         boolean not null default true,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (owner, name)
);

create table if not exists public.fin_financial_goals (
  id                  bigint generated by default as identity primary key,
  owner               uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name                text not null,
  goal_type           text not null,
  target_amount       numeric(14,2) not null,
  current_amount      numeric(14,2) not null default 0,
  recommended_monthly numeric(14,2) not null default 0,
  user_monthly_target numeric(14,2) not null default 0,
  target_date         date,
  linked_account_id   bigint references public.fin_accounts(id) on delete set null,
  is_active           boolean not null default true,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  unique (owner, name)
);

create table if not exists public.fin_retirement_contributions (
  id                bigint generated by default as identity primary key,
  owner             uuid not null default auth.uid() references auth.users(id) on delete cascade,
  contribution_date date not null,
  account_id        bigint not null references public.fin_accounts(id) on delete cascade,
  employee_amount   numeric(14,2) not null,
  employer_match    numeric(14,2) not null default 0,
  contribution_type text not null default 'roth',
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- App state: settings, setup progress, snapshots
-- ---------------------------------------------------------------------------

create table if not exists public.fin_settings (
  id          bigint generated by default as identity primary key,
  owner       uuid not null default auth.uid() references auth.users(id) on delete cascade,
  key         text not null,
  value       text not null,
  value_type  text not null default 'string',
  label       text not null,
  description text,
  category    text not null default 'general',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (owner, key)
);

create table if not exists public.fin_setup_progress (
  id             bigint generated by default as identity primary key,
  owner          uuid not null default auth.uid() references auth.users(id) on delete cascade,
  current_step   int not null default 1,
  completed      boolean not null default false,
  history_option text not null default 'start_today',
  setup_date     date,
  completed_at   timestamptz,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  unique (owner)
);

create table if not exists public.fin_monthly_snapshots (
  id             bigint generated by default as identity primary key,
  owner          uuid not null default auth.uid() references auth.users(id) on delete cascade,
  snapshot_month date not null,
  net_worth      numeric(14,2) not null,
  liquid_cash    numeric(14,2) not null,
  income         numeric(14,2) not null,
  spending       numeric(14,2) not null,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  unique (owner, snapshot_month)
);

-- ---------------------------------------------------------------------------
-- Investments
-- ---------------------------------------------------------------------------

create table if not exists public.fin_investment_accounts (
  id            bigint generated by default as identity primary key,
  owner         uuid not null default auth.uid() references auth.users(id) on delete cascade,
  account_id    bigint not null unique references public.fin_accounts(id) on delete cascade,
  tax_treatment text not null
);

create table if not exists public.fin_securities (
  id            bigint generated by default as identity primary key,
  owner         uuid not null default auth.uid() references auth.users(id) on delete cascade,
  symbol        text not null,
  name          text not null,
  security_type text not null,
  unique (owner, symbol)
);

create table if not exists public.fin_investment_holdings (
  id                    bigint generated by default as identity primary key,
  owner                 uuid not null default auth.uid() references auth.users(id) on delete cascade,
  investment_account_id bigint not null references public.fin_investment_accounts(id) on delete cascade,
  security_id           bigint not null references public.fin_securities(id) on delete cascade,
  quantity              numeric(20,8) not null,
  cost_basis            numeric(14,2) not null,
  as_of_date            date,
  unique (investment_account_id, security_id)
);

create table if not exists public.fin_investment_transactions (
  id                    bigint generated by default as identity primary key,
  owner                 uuid not null default auth.uid() references auth.users(id) on delete cascade,
  investment_account_id bigint not null references public.fin_investment_accounts(id) on delete cascade,
  security_id           bigint references public.fin_securities(id) on delete set null,
  transaction_date      date not null,
  transaction_type      text not null,
  amount                numeric(14,2) not null,
  quantity              numeric(20,8),
  fees                  numeric(14,2) not null default 0,
  notes                 text
);

create table if not exists public.fin_security_prices (
  id          bigint generated by default as identity primary key,
  owner       uuid not null default auth.uid() references auth.users(id) on delete cascade,
  security_id bigint not null references public.fin_securities(id) on delete cascade,
  price_date  date not null,
  price       numeric(20,8) not null,
  source      text not null default 'manual',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (security_id, price_date)
);

create index if not exists fin_security_prices_date_idx on public.fin_security_prices(owner, price_date);

create table if not exists public.fin_investment_snapshots (
  id                    bigint generated by default as identity primary key,
  owner                 uuid not null default auth.uid() references auth.users(id) on delete cascade,
  investment_account_id bigint not null references public.fin_investment_accounts(id) on delete cascade,
  security_id           bigint not null references public.fin_securities(id) on delete cascade,
  snapshot_date         date not null,
  quantity              numeric(20,8) not null,
  price                 numeric(20,8) not null,
  market_value          numeric(14,2) not null,
  cost_basis            numeric(14,2) not null,
  source                text not null default 'manual',
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  unique (investment_account_id, security_id, snapshot_date)
);

create index if not exists fin_investment_snapshots_date_idx on public.fin_investment_snapshots(owner, snapshot_date);

-- ---------------------------------------------------------------------------
-- Imports review + AI
-- ---------------------------------------------------------------------------

create table if not exists public.fin_ai_reviews (
  id                       bigint generated by default as identity primary key,
  owner                    uuid not null default auth.uid() references auth.users(id) on delete cascade,
  ai_import_id             bigint not null references public.fin_ai_imports(id) on delete cascade,
  transaction_id           bigint references public.fin_transactions(id) on delete set null,
  status                   text not null default 'needs_review',
  suggested_payload        text,
  confidence               numeric(5,4),
  reason                   text,
  duplicate_transaction_id bigint references public.fin_transactions(id) on delete set null,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now()
);

create table if not exists public.fin_merchant_rules (
  id                  bigint generated by default as identity primary key,
  owner               uuid not null default auth.uid() references auth.users(id) on delete cascade,
  merchant_pattern    text not null,
  normalized_merchant text not null,
  category_id         bigint references public.fin_transaction_categories(id) on delete set null,
  subcategory_id      bigint references public.fin_transaction_categories(id) on delete set null,
  is_transfer         boolean not null default false,
  times_applied       int not null default 0,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  unique (owner, merchant_pattern)
);

create table if not exists public.fin_recurring_suggestions (
  id              bigint generated by default as identity primary key,
  owner           uuid not null default auth.uid() references auth.users(id) on delete cascade,
  merchant        text not null,
  suggestion_type text not null,
  status          text not null default 'needs_review',
  amount          numeric(14,2),
  previous_amount numeric(14,2),
  evidence        text,
  transaction_id  bigint references public.fin_transactions(id) on delete set null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create table if not exists public.fin_monthly_ai_insights (
  id              bigint generated by default as identity primary key,
  owner           uuid not null default auth.uid() references auth.users(id) on delete cascade,
  snapshot_month  date not null,
  status          text not null default 'metrics_ready',
  metrics_json    text not null,
  commentary_json text,
  source          text not null default 'manual',
  model           text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (owner, snapshot_month)
);

-- ---------------------------------------------------------------------------
-- Money flow: month plans + paycheck allocations
-- ---------------------------------------------------------------------------

create table if not exists public.fin_month_plans (
  id                  bigint generated by default as identity primary key,
  owner               uuid not null default auth.uid() references auth.users(id) on delete cascade,
  plan_month          date not null,
  status              text not null default 'open',
  closed_at           timestamptz,
  swept_amount        numeric(14,2) not null default 0,
  swept_to_account_id bigint references public.fin_accounts(id) on delete set null,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  unique (owner, plan_month)
);

create table if not exists public.fin_paycheck_allocations (
  id                     bigint generated by default as identity primary key,
  owner                  uuid not null default auth.uid() references auth.users(id) on delete cascade,
  paycheck_id            bigint not null references public.fin_paychecks(id) on delete cascade,
  plan_month             date not null,
  target_kind            text not null,
  target_id              bigint,
  label                  text not null,
  amount                 numeric(14,2) not null default 0,
  requested_amount       numeric(14,2) not null default 0,
  destination_account_id bigint references public.fin_accounts(id) on delete set null,
  transfer_id            bigint references public.fin_transfers(id) on delete set null,
  note                   text,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  unique (paycheck_id, target_kind, target_id, label)
);

create index if not exists fin_paycheck_allocations_month_idx on public.fin_paycheck_allocations(owner, plan_month);
create index if not exists fin_paycheck_allocations_kind_idx  on public.fin_paycheck_allocations(owner, target_kind);
create index if not exists fin_month_plans_month_idx          on public.fin_month_plans(owner, plan_month);

-- ---------------------------------------------------------------------------
-- Row Level Security — owner-scoped, authenticated only.
-- `anon` gets nothing: the public anon key alone cannot read a single row.
-- ---------------------------------------------------------------------------

do $$
declare
  t text;
  tables text[] := array[
    'fin_accounts', 'fin_account_balances', 'fin_transaction_categories',
    'fin_transactions', 'fin_transfers', 'fin_paychecks', 'fin_paycheck_deductions',
    'fin_pto_entries', 'fin_subscriptions', 'fin_recurring_expenses', 'fin_sinking_funds',
    'fin_financial_goals', 'fin_retirement_contributions', 'fin_settings',
    'fin_setup_progress', 'fin_monthly_snapshots', 'fin_investment_accounts',
    'fin_securities', 'fin_investment_holdings', 'fin_investment_transactions',
    'fin_security_prices', 'fin_investment_snapshots', 'fin_ai_imports',
    'fin_ai_reviews', 'fin_merchant_rules', 'fin_recurring_suggestions',
    'fin_monthly_ai_insights', 'fin_month_plans', 'fin_paycheck_allocations'
  ];
begin
  foreach t in array tables loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on public.%I from anon', t);
    execute format('drop policy if exists %I on public.%I', t || '_owner', t);
    execute format(
      'create policy %I on public.%I for all to authenticated using (owner = auth.uid()) with check (owner = auth.uid())',
      t || '_owner', t
    );
  end loop;
end $$;

-- updated_at triggers for every table that carries the column
do $$
declare
  t text;
begin
  for t in
    select c.table_name
    from information_schema.columns c
    where c.table_schema = 'public'
      and c.column_name = 'updated_at'
      and c.table_name like 'fin\_%'
  loop
    execute format('drop trigger if exists %I on public.%I', t || '_touch', t);
    execute format(
      'create trigger %I before update on public.%I for each row execute function public.fin_touch_updated_at()',
      t || '_touch', t
    );
  end loop;
end $$;


-- ---------------------------------------------------------------------------
-- After a bulk load with explicit ids, move each identity sequence past the
-- highest id present. Without this the next natural insert would collide with
-- a restored row and fail on the primary key.
-- ---------------------------------------------------------------------------

create or replace function public.fin_resync_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  t text;
  seq text;
  max_id bigint;
begin
  for t in
    select c.table_name
    from information_schema.columns c
    where c.table_schema = 'public'
      and c.column_name = 'id'
      and c.table_name like 'fin\_%'
  loop
    seq := pg_get_serial_sequence('public.' || quote_ident(t), 'id');
    if seq is null then
      continue;
    end if;
    execute format('select coalesce(max(id), 0) from public.%I', t) into max_id;
    perform setval(seq, greatest(max_id, 1), max_id > 0);
  end loop;
end;
$$;

grant execute on function public.fin_resync_sequences() to authenticated;
