#!/usr/bin/env python3
"""Generate a one-time SQL migration from the old NexaFi SQLite database.

Reads the local nexafi.db that the Python app used and writes a single SQL file
to paste into the Supabase SQL editor. Run it once, after finance_setup.sql.

    python3 scripts/migrate-nexafi-sqlite.py \
        --database ~/Library/Application\\ Support/NexaFi/data/nexafi.db \
        --owner-email you@example.com \
        --out supabase/finance_migrate_data.sql

Two things make the output safe to run:

* Ids are preserved. Every relationship between these tables is by integer id,
  so renumbering during the copy would silently break foreign keys. The schema's
  identity columns are `by default` precisely so this is possible, and the file
  ends by resyncing the sequences past the highest imported id.

* Only columns present in BOTH the SQLite table and the Postgres table are
  copied. The local database is from an earlier version of the app and is
  missing some columns that were added later; those simply take their Postgres
  defaults instead of failing the import.
"""

from __future__ import annotations

import argparse
import sqlite3
import sys
from pathlib import Path

# SQLite table -> Postgres table. Order is dependency order: a table only
# references ones above it, so inserting top-down never hits a missing parent.
TABLES: list[tuple[str, str]] = [
    ("accounts", "fin_accounts"),
    ("transaction_categories", "fin_transaction_categories"),
    ("account_balances", "fin_account_balances"),
    ("ai_imports", "fin_ai_imports"),
    ("transactions", "fin_transactions"),
    ("transfers", "fin_transfers"),
    ("paychecks", "fin_paychecks"),
    ("paycheck_deductions", "fin_paycheck_deductions"),
    ("subscriptions", "fin_subscriptions"),
    ("recurring_expenses", "fin_recurring_expenses"),
    ("sinking_funds", "fin_sinking_funds"),
    ("financial_goals", "fin_financial_goals"),
    ("retirement_contributions", "fin_retirement_contributions"),
    ("monthly_snapshots", "fin_monthly_snapshots"),
    ("investment_accounts", "fin_investment_accounts"),
    ("securities", "fin_securities"),
    ("security_prices", "fin_security_prices"),
    ("investment_holdings", "fin_investment_holdings"),
    ("investment_snapshots", "fin_investment_snapshots"),
    ("investment_transactions", "fin_investment_transactions"),
    ("ai_reviews", "fin_ai_reviews"),
    ("merchant_rules", "fin_merchant_rules"),
    ("recurring_suggestions", "fin_recurring_suggestions"),
    ("monthly_ai_insights", "fin_monthly_ai_insights"),
    ("settings", "fin_settings"),
    ("setup_progress", "fin_setup_progress"),
    ("month_plans", "fin_month_plans"),
    ("paycheck_allocations", "fin_paycheck_allocations"),
]

# Columns stored as 0/1 in SQLite that are real booleans in Postgres.
BOOLEAN_COLUMNS = {
    "is_liability", "include_in_net_worth", "is_active", "autopay_enabled",
    "is_transfer", "is_recurring", "review_required", "is_pre_tax",
    "is_variable", "completed",
}

# The Postgres tables have these; SQLite may not. Never copied either way.
SKIP_COLUMNS = {"owner"}


def sqlite_columns(connection: sqlite3.Connection, table: str) -> list[str] | None:
    """Column names for a SQLite table, or None if the table does not exist."""
    rows = connection.execute(f"PRAGMA table_info({table})").fetchall()
    if not rows:
        return None
    return [row[1] for row in rows]


def quote(value, column: str) -> str:
    if value is None:
        return "null"
    if column in BOOLEAN_COLUMNS:
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value).replace("'", "''")
    return f"'{text}'"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--database", required=True, type=Path)
    parser.add_argument("--owner-email", required=True)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()

    if not args.database.exists():
        print(f"No database at {args.database}", file=sys.stderr)
        return 1

    connection = sqlite3.connect(f"file:{args.database}?mode=ro", uri=True)
    connection.row_factory = sqlite3.Row

    email = args.owner_email.replace("'", "''")
    lines: list[str] = [
        "-- One-time data migration from the local NexaFi SQLite database.",
        "-- Generated by scripts/migrate-nexafi-sqlite.py. Run AFTER finance_setup.sql.",
        "--",
        "-- Safe to re-run only against an empty finance database: it inserts rows with",
        "-- explicit ids and will collide with anything already imported.",
        "",
        "do $$",
        "declare",
        "  owner_id uuid;",
        "begin",
        f"  select id into owner_id from auth.users where email = '{email}';",
        "  if owner_id is null then",
        f"    raise exception 'No Supabase auth user with email {email}. "
        "Create the account first, then re-run.';",
        "  end if;",
        "",
    ]

    total_rows = 0
    summary: list[str] = []

    for sqlite_table, pg_table in TABLES:
        columns = sqlite_columns(connection, sqlite_table)
        if columns is None:
            summary.append(f"  {sqlite_table}: table absent, skipped")
            continue

        usable = [c for c in columns if c not in SKIP_COLUMNS]
        rows = connection.execute(f"SELECT * FROM {sqlite_table}").fetchall()
        if not rows:
            summary.append(f"  {sqlite_table}: 0 rows")
            continue

        column_list = ", ".join(["owner", *(f'"{c}"' for c in usable)])
        lines.append(f"  -- {sqlite_table} -> {pg_table} ({len(rows)} rows)")
        lines.append(f"  insert into public.{pg_table} ({column_list}) values")

        values: list[str] = []
        for row in rows:
            cells = ", ".join(quote(row[c], c) for c in usable)
            values.append(f"    (owner_id, {cells})")
        lines.append(",\n".join(values) + ";")
        lines.append("")

        total_rows += len(rows)
        summary.append(f"  {sqlite_table}: {len(rows)} rows")

    # The oldest local databases predate the setup_progress table. If accounts
    # exist, setup demonstrably happened, so record that rather than sending the
    # person back through a wizard for data they already have.
    if sqlite_columns(connection, "setup_progress") is None and total_rows > 0:
        lines.append("  -- setup_progress absent in the source database")
        lines.append("  -- (predates that table); recorded as complete because accounts exist.")
        lines.append(
            "  insert into public.fin_setup_progress "
            "(owner, current_step, completed, history_option, setup_date, completed_at) "
            "values (owner_id, 8, true, 'start_today', current_date, now());"
        )
        lines.append("")
        summary.append("  setup_progress: synthesized as complete")

    lines.extend(
        [
            "end $$;",
            "",
            "-- Move every identity sequence past the highest imported id, so the next",
            "-- row created in the app does not collide with a migrated one.",
            "select public.fin_resync_sequences();",
            "",
        ]
    )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote {args.out} ({total_rows} rows)")
    print("\n".join(summary))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
